<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-SecureChat.Web-8314b1c5-aea9-40eb-8123-2f497293cdbc</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.Identity.MongoDbCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.21" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.10" />
    <PackageReference Include="MongoDB.Driver" Version="2.27.1" />
  </ItemGroup>

</Project>
